### PR TITLE
get version id from git

### PR DESCRIPTION
**Pull request by holmeso**
updated build.gradle to use `git rev-parse --short HEAD` rather than `svn info .`

### CODE REVIEW

**Comment by holmeso** [comment]
I'm going to add a gradle wrapper so that users don't need to download gradle themselves

**Comment by holmeso** [comment]
OK, should now be able to kick off the build be running `./gradlew` which will pull down the required version of gradle (if it isn't already installed on the machine)

**Comment by CanWood** [comment]
I've ensured I have a java 1.8 in my path before running gradlew, but hit the following:

```
Picked up JAVA_TOOL_OPTIONS:  -XX:+UseSerialGC
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by CanWood** [comment]
Successfully fetched gradle on a host with correct proxy settings.  Build failed with the following:

`
A problem occurred starting process 'Gradle Test Executor 2'
org.gradle.process.internal.ExecException: A problem occurred starting process 'Gradle Test Executor 2'
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:231)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:355)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:85)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/software/java/jdk1.8.0_152/bin/java'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:67)
        ... 7 more
Caused by: java.io.IOException: Cannot run program "/software/java/jdk1.8.0_152/bin/java" (in directory "/mnt/lustre/working/genomeinfo/users/scottW/devel/adamajava/qannotate/build/classes/test"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more
`

**Comment by holmeso** [comment]
updated the wrapper to point to version 2.14 of gradle, which (hopefully) doesn't exhibit this behaviour

**Comment by CanWood** [comment]
Two tests failed, 

    OptionsTest. testValidAddOptions
    PileupPipelineTest. testModes

with the following error:
`org.qcmg.pileup.QPileupException: Exception caught for bam file: /mnt/lustre/working/genomeinfo/users/scottW/devel/adamajava/qpileup/build/resources/test/resources/test.bam. The error is org.qcmg.pileup.QPileupException: Index for /mnt/lustre/working/genomeinfo/users/scottW/devel/adamajava/qpileup/build/resources/test/resources/test.bam is older than the bam file`

**Comment by holmeso** [comment]
actually Scott, if you could give me the full stack trace that would be great - I can't recreate (locally or on the cluster)

**Comment by CanWood** [comment]
4 successful builds and I can't recreate the bam vs bai timing issue.  Not letting it hold things up.

**Pull request merged**
