### PR TITLE
removed unnecessary null check of acc in getFormatFilter

### LINKED ISSUE #34: unnecessary null check
In qsnp's `GenotypeUtil` class, there is a redundant check for null in the `getFormatFilter` method.
The parameter `acc` is checked to see if it is null initially. It is then checked again a few lines later, which is unnecessary

The expected behaviour is that `acc` should only be checked for null-ness once

### PR DESCRIPTION
**Pull request by sarahk2019**
fixes #34 
acc argument is already checked that it is not null in the first line so changed initialisation of totalReadCount variable to not check for null acc, and removed null check of acc a few lines down.

### CODE REVIEW

**Comment by delocalizer** [comment]
Eep I was too slow... Looks like the new version of `GenotypeUtil.java` is full of Windows line endings

**Comment by holmeso** [comment]
where do you see the Windows line endings? It looks ok when viewing changes and looking at the file (normal and raw).
Build seems happy too...

**Comment by delocalizer** [comment]
https://github.com/AdamaJava/adamajava/pull/35/files
And git diff

**Comment by delocalizer** [comment]
475 lines removed, 478 lines added

**Comment by delocalizer** [comment]
@holmeso @sarahk2019  actually the dos line endings _are_ in now master version; I just hadn't pull'ed the changes since branch was merged in. This is actually sort of good news, since it means there isn't some undocumented magic "line ending fixer-upper" being applied.

**Pull request merged**
