### PR TITLE
moved ISizeCluster from internal repo to qmule

### PR DESCRIPTION
**Pull request by holmeso**
# Description

ISizeCluster is used by the wdl pipeline and if we are to use it externally, it needs to be publicly available.
And so, the class ( and its accompanying test) is moving to github from the internal repo.

## Type of change

Refactor (move)

# How Has This Been Tested?

ISizeClusterTest has also been moved from the internal repo to github

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ChristinaXu2017** [comment]
ISizeCluster is used in our WDL pipeline,   grab some existing output from the previous run, and then compare the output from this migrated ISizeCluster to the existing one.

**Comment by holmeso** [comment]
> ISizeCluster is used in our WDL pipeline, grab some existing output from the previous run, and then compare the output from this migrated ISizeCluster to the existing one.

The code hasn't changed - the location has

**Comment by ChristinaXu2017** [comment]
> The code hasn't changed - the location has

it may just copy & paste, but the reviewer still has to check the function. run a real data will be the most efficient way to check whether this tool keeps the same function after migrant.

**Comment by holmeso** [comment]
> > The code hasn't changed - the location has
> 
> it may just copy & paste, but the reviewer still has to check the function. run a real data will be the most efficient way to check whether this tool keeps the same function after migrant.

Here is the output for your perusal:

```
java -Xmx2G -cp ~/qmule/bin/qmule.jar org.qcmg.qmule.ISizeCluster /working/genomeinfo/cromwell-test/cromwell-executions/somaticDnaFastqToMaf/bc099e7a-d4e9-4b5d-8d4e-ec228c46a573/call-testISize/inputs/-369381563/6bf31f72-53d2-42e8-ae77-e8651a109fb5.bam.qp.xml  | grep "RG"
Picked up JAVA_TOOL_OPTIONS:  -XX:+UseSerialGC
RG=0a93c66d-909c-4fed-842b-ac97bf45aaf0 LB=7 UB=873
RG=374ed445-b8ee-4a1d-9337-f3fdd661f408 LB=11 UB=867
RG=69f81d0d-c430-4a6f-9ccd-05ea88b22c1d LB=18 UB=849
RG=764841a0-33ba-4756-90d2-5339a510ce0f LB=15 UB=848
RG=b0e75159-c488-4c0b-90fc-d56230f3e73e LB=15 UB=863
RG=cd90dd75-8a1f-4fd0-a352-0364d8dd5300 LB=15 UB=857
RG=d95d01d1-13ea-4fe3-9c7a-168fd789e8be LB=15 UB=849
RG=e293eaad-7752-4eed-9674-234a023295c5 LB=18 UB=858
RG=fa428f11-7798-4cf6-8519-39d4dac95f04 LB=15 UB=854
```
and
```
java -Xmx2G -cp /software/genomeinfo/java/nightly/trunk/adama/build/lib/genomiqatools-0.1.jar com.genomiqa.tools.ISizeCluster /working/genomeinfo/cromwell-test/cromwell-executions/somaticDnaFastqToMaf/bc099e7a-d4e9-4b5d-8d4e-ec228c46a573/call-testISize/inputs/-369381563/6bf31f72-53d2-42e8-ae77-e8651a109fb5.bam.qp.xml  | grep "RG"
Picked up JAVA_TOOL_OPTIONS:  -XX:+UseSerialGC
RG=0a93c66d-909c-4fed-842b-ac97bf45aaf0 LB=7 UB=873
RG=374ed445-b8ee-4a1d-9337-f3fdd661f408 LB=11 UB=867
RG=69f81d0d-c430-4a6f-9ccd-05ea88b22c1d LB=18 UB=849
RG=764841a0-33ba-4756-90d2-5339a510ce0f LB=15 UB=848
RG=b0e75159-c488-4c0b-90fc-d56230f3e73e LB=15 UB=863
RG=cd90dd75-8a1f-4fd0-a352-0364d8dd5300 LB=15 UB=857
RG=d95d01d1-13ea-4fe3-9c7a-168fd789e8be LB=15 UB=849
RG=e293eaad-7752-4eed-9674-234a023295c5 LB=18 UB=858
RG=fa428f11-7798-4cf6-8519-39d4dac95f04 LB=15 UB=854
```

**Review by ChristinaXu2017 — APPROVED** [review]
looks good!

**Pull request merged**
