### PR TITLE
Fixes for v1.0 of mkdocs documentation.

### PR DESCRIPTION
**Pull request by grendeloz**
# Description

Fixes some bad links in documentation and adds extra files to the navigation bar so it's simpler to find additional pages.

Fixes # (issue)

N/A - this branch fixes unlogged errors in the markdown documentation.

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Changes were tested offline using "mkdocs serve".

- [X] All new links were followed in testing.

# Checklist:

- [N/A] My code follows the style guidelines of this project
- [N/A] I have performed a self-review of my own code
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [N/A] My changes generate no new warnings
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ChristinaXu2017 — COMMENTED** [review]
I am looking at the difference between the master and mkdoc_fixes branches.  In the master branch,  If I click "qbasepileup"  in page "adamajava/docs/intro.md", it will enter into the subfolder " adamajava/docs/qbasepileup/", where four *.md file reside;  In the mkdoc_fixes branch, if I do so, it will go back to " adamajava/qbasepileup/", where only code exists but no MD file. 
 
I am not sure it is just a draft, you will move these MD files between folders, or there is another purpose.

**Comment by ChristinaXu2017** [comment]
should we delete the old READMD.md under adamajava root?
should the mkdocs.yml move to adamaJava/docs ?

**Comment by grendeloz** [comment]
This is part of the mkdocs trick - you cannot use the source files (.md) "as is" to test the documentation because the source files are rearranged and rendered to HTML by mkdocs.  To test the docs, you must check them out, install mkdocs, run "mkdocs serve" (see my comment in testing) at the docroot (where mkdocs.yaml is found) which starts a localhost webserver, and then view the rendered docs in a browser pointed at the localhost server.  It would be great if you could install mkdocs and do the testing on the new branch.

**Comment by grendeloz** [comment]
Once the docs are correct at readthedocs I will definitely edit the README to point people to readthedocs. I think the mkdocs.yaml is in the right place - I think part of the original problem was that I had the entire docs directory one level too deep for what readthedocs expected. I have to keep remembering that readthedocs uses mkdocs BUT they have their own expectations about how things should be laid out and used so just because I have done something that is legal in mkdocs, doesn't mean it works perfectly in readthedocs. For now, I am trying to do what readthedocs expects and I can deal with differences between mkdocs and readthedocs/mkdocs later.  Most readthedocs sites use sphinx not mkdocs so I have not been able to find good examples of big documentation trees using mkdocs at readthedocs.  Based on the examples I can find, this new branch is legal in mkdocs (where I have tested it) and hopefully also works with readthedocs/mkdocs (where I don't know how to test it until after the branch has been pull'ed).

**Review by ChristinaXu2017 — APPROVED** [review]

**Pull request merged**
